
# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'fivetran_dbt'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'fivetran_dbt'

# These configurations specify where dbt should look for different types of files.
# The `model-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

vars:
    amazon_ads_schema: amazon_ads
#    amazon_ads_database: your_database_name

    apple_search_ads_schema: apple_search_ads
#    apple_search_ads_database: your_database_name

    facebook_ads_schema: s_facebook_ads
#    facebook_ads_database: your_database_name 

    google_ads_schema: s_google_ads
#    google_ads_database: your_database_name 

    microsoft_ads_schema: bingads
#    microsoft_ads_database: your_database_name

    linkedin_ads_schema: s_linkedin_ads 
#    linkedin_ads_database: your_database_name  

    pinterest_schema: s_pinterest_ads
#    pinterest_database: your_database_name 

    twitter_ads_schema: s_twitter_ads
#    twitter_ads_database: your_database_name  

    snapchat_schema: snapchat_ads
#    snapchat_database: your_database_name 
    
    tiktok_ads_schema: tiktok_ads
#    tiktok_ads_database: your_database_name

    ad_reporting__amazon_ads_enabled: False # by default this is assumed to be True
    
    ad_reporting__apple_search_ads_enabled: False # by default this is assumed to be True
    
    ad_reporting__microsoft_ads_enabled: False # by default this is assumed to be True
    
    ad_reporting__facebook_ads_enabled: False # by default this is assumed to be True
    
    ad_reporting__snapchat_ads_enabled: False # by default this is assumed to be True
    
    ad_reporting__tiktok_ads_enabled: False # by default this is assumed to be True

